---

- include: local-eap6.yml

- include: local-eap7.yml

# Setup the controller machine
- hosts: localhost
  connection: local
  roles:
    # Build some sample applications.
    - {role: "java-demo-app"}
